# Generated by Django 3.2.2 on 2022-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='', max_length=7, verbose_name='Тип категории'),
            preserve_default=False,
        ),
    ]
