# Generated by Django 3.2.2 on 2022-07-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0002_auto_20220713_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pockets.transactioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=7, verbose_name='Тип операции'),
        ),
    ]
