# Generated by Django 3.2.2 on 2022-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
