# Generated by Django 3.2.2 on 2022-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0005_alter_transactioncategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
