# Generated by Django 3.2.2 on 2022-07-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0012_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата операции'),
        ),
    ]
