# Generated by Django 3.2.2 on 2022-07-18 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0013_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата операции'),
        ),
    ]
